#pragma once 
#if defined(IS_DESKTOP)
#  define PROGMEM
#else
#  include "pgmspace.h"
#endif
extern const unsigned char bassdrum_raw[];
extern const unsigned char britestk_raw[];
extern const unsigned char cowbell1_raw[];
extern const unsigned char crashcym_raw[];
extern const unsigned char dope_raw[];
extern const unsigned char eee_raw[];
extern const unsigned char fwavblnk_raw[];
extern const unsigned char halfwave_raw[];
extern const unsigned char hihatcym_raw[];
extern const unsigned char impuls10_raw[];
extern const unsigned char impuls20_raw[];
extern const unsigned char impuls40_raw[];
extern const unsigned char mand1_raw[];
extern const unsigned char mand2_raw[];
extern const unsigned char mand3_raw[];
extern const unsigned char mand4_raw[];
extern const unsigned char mand5_raw[];
extern const unsigned char mand6_raw[];
extern const unsigned char mand7_raw[];
extern const unsigned char mand8_raw[];
extern const unsigned char mand9_raw[];
extern const unsigned char mand10_raw[];
extern const unsigned char mand11_raw[];
extern const unsigned char mand12_raw[];
extern const unsigned char mandpluk_raw[];
extern const unsigned char marmstk1_raw[];
extern const unsigned char ooo_raw[];
extern const unsigned char peksblnk_raw[];
extern const unsigned char ppksblnk_raw[];
extern const unsigned char ridecymb_raw[];
extern const unsigned char silence_raw[];
extern const unsigned char sineblnk_raw[];
extern const unsigned char sinewave_raw[];
extern const unsigned char snardrum_raw[];
extern const unsigned char snglpeak_raw[];
extern const unsigned char tambourn_raw[];
extern const unsigned char tomhidrm_raw[];
extern const unsigned char tomlowdr_raw[];
extern const unsigned char tommiddr_raw[];
extern const unsigned char twopeaks_raw[];

extern unsigned int bassdrum_raw_len;
extern unsigned int britestk_raw_len;
extern unsigned int cowbell1_raw_len;
extern unsigned int crashcym_raw_len ;
extern unsigned int dope_raw_len;
extern unsigned int eee_raw_len;
extern unsigned int fwavblnk_raw_len;
extern unsigned int halfwave_raw_len;
extern unsigned int hihatcym_raw_len;
extern unsigned int impuls10_raw_len;
extern unsigned int impuls20_raw_len;
extern unsigned int impuls40_raw_len;
extern unsigned int mand1_raw_len;
extern unsigned int mand2_raw_len;
extern unsigned int mand3_raw_len;
extern unsigned int mand4_raw_len;
extern unsigned int mand5_raw_len;
extern unsigned int mand6_raw_len;
extern unsigned int mand7_raw_len;
extern unsigned int mand8_raw_len;
extern unsigned int mand9_raw_len;
extern unsigned int mand10_raw_len;
extern unsigned int mand11_raw_len;
extern unsigned int mand12_raw_len;
extern unsigned int mandpluk_raw_len;
extern unsigned int marmstk1_raw_len;
extern unsigned int ooo_raw_len;
extern unsigned int peksblnk_raw_len;
extern unsigned int ppksblnk_raw_len;
extern unsigned int ridecymb_raw_len;
extern unsigned int silence_raw_len;
extern unsigned int sineblnk_raw_len;
extern unsigned int sinewave_raw_len;
extern unsigned int snardrum_raw_len;
extern unsigned int snglpeak_raw_len;
extern unsigned int tambourn_raw_len;
extern unsigned int tomhidrm_raw_len;
extern unsigned int tomlowdr_raw_len;
extern unsigned int tommiddr_raw_len;
extern unsigned int twopeaks_raw_len;